# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: JMH Run

on:
  - push
  - workflow_dispatch  # enables manually triggered runs

jobs:
  build:
    runs-on: ubuntu-latest

    name: Run JMH Benchmark
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'zulu'
          java-package: jdk
          architecture: x64
          cache: 'maven'

      - name: Grant Execute Permission for Script
        run: chmod +x benchmark.sh

      - name: Run the Benchmark
        run: ./benchmark.sh

      - name: Upload JMH Results
        uses: actions/upload-artifact@v4
        with:
          name: jmh-results
          path: reports/*.json
