# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: JMH Run

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8.0.212
          java-package: jdk
          architecture: x64

      - name: Grant Execute Permission for Script
        run: chmod +x benchmark.sh

      - name: Run the Benchmark
        run: ./benchmark.sh

      - name: Upload JMH Results
        uses: actions/upload-artifact@v2
        with:
          name: jmh-results
          path: reports/*.json