# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: JMH Run

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Run JMH Benchmark
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'zulu'
          java-package: jdk
          architecture: x64
          cache: 'maven'

      - name: Build with Maven
        run: mvn -pl '!nitrite-java/nitrite-native-tests,!nitrite-java/potassium-nitrite' clean install -DskipTests

      - name: Prepare the output dir
        run: mkdir reports

      - name: Run the Benchmark with stack profiler
        run: java -jar nitrite-v4/target/benchmarks.jar -rf json -rff reports/nitrite-v4-subset.json -prof stack

      - name: Upload JMH Results
        uses: actions/upload-artifact@v4
        with:
          name: jmh-results
          path: reports/*.json
